version: '3.7'
services:
  jenkins:
  #  image: jenkins/jenkins
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
    #  - /var/jenkins_home:/data/jenkins
      - ./data/jenkins:/var/jenkins_home
    restart: unless-stopped
    networks:
      - default


  nexus:
      image: sonatype/nexus3
      container_name: nexus
  #    build:
  #      context: .
      ports:
        - 8081:8081
      volumes:
        # - /nexus-data:/data/nexus
        - ./data/nexus:/nexus-data
      networks:
        - default

networks:
  default:
