FROM jenkins

USER root

RUN apt-get update
RUN apt-get install -y git
RUN apt-get update && install software-properties-common
RUN apt-add-repository --yes --update ppa:ansible/ansible
RUN apt install ansible

# Setup Maven
ENV MAVEN_VERSION 3.6.0

RUN curl -fsSL http://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar xzf - -C /usr/share \
  && mv /usr/share/apache-maven-$MAVEN_VERSION /usr/share/maven \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven
COPY settings.xml /root/.m2/settings.xml

# Configure ansible
COPY ./ansible/. /etc/ansible

# Configure Jenkins
COPY plugins.txt ./plugins.txt
COPY config.groovy ./config.groovy
RUN /usr/local/bin/plugins.sh ./plugins.txt

# Volumes
VOLUME /root/.ssh

# Start it all
ENTRYPOINT ["/usr/local/bin/init.sh"]
